\documentclass[11pt, oneside]{article}
\usepackage{geometry}
\geometry{letterpaper}
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage[affil-it]{authblk}
\usepackage{verbatim}

\title{CompGO vignette}
\author{Sam Bassett, Ash Waardenberg}
\affil{Developmental and Stem Cell Biology Lab,\\Victor Chang Cardiac Research Institute,\\Darlinghurst, Sydney, Australia}
\date{}

\begin{document}
\maketitle
%\VignetteIndexEntry{Introduction}
\section{Introduction}
This package contains functions to accomplish several tasks relating to gene ontology enrichment comparison and visualisation. It interfaces with rtracklayer and VariantAnnotation to easily annotate .bed files with genes, and with RDAVIDWebService to generate functional annotation charts based on these gene lists. From here, we provide several methods for visualisation, including viewing the GO term hierarchy in two samples using a directed acyclic graph (DAG), performing a z-score standardisation on the GO terms returned from DAVID, comparing these directly using a pairwise scatterplot with linear fit and Jaccard metric and clustering multiple inputs into a dendrogram.\\

\section{Generation of Gene Ontology data}

The first step in this analysis pipeline is generating the individual Gene Ontology data for each dataset. We provide an interface to generate a list of genes from input .bed coordinates with the function anotateBedFromDb, which can take either a system path or a GRanges object as input:
<<>>=
library(CompGO)
library(TxDb.Mmusculus.UCSC.mm9.knownGene)
data(bed.sample)
# Here we create the GRanges object:
sample.range = GRanges(seqnames=bed.sample$chr,
    IRanges(start=bed.sample$start, end=bed.sample$end))
# Note that the window around the .bed region beyond which
# genes are cutoff is 5kb, this is modifiable
sample.annotated = annotateBedFromDb(gRanges = sample.range,
    db = TxDb.Mmusculus.UCSC.mm9.knownGene)
head(sample.annotated)
@

Once we have this annotated GRanges object, we can use the list of genes contained within to query DAVID and return the full functional annotation chart. Note that there are several parameters available for tweaking here, especially rawValues - this parameter tells DAVID to do no thresholding of results whatsoever, giving the user of this package the power to perform their own thresholding. Since DAVID requires registration before the use of their Web Service R package, you should register first then substitute the placeholder email for your own.
<<>>=
# fnAnot = getFnAnot_genome(sample.annotated$gene_id,
#    email = "PLaceholder@inst.edu", listName="sample")
# We instead use examples from the RDAVIDWebService package,
# but without KEGG data:
data(funChart1)
data(funChart2)
funChart1 = subset(funChart1, Category %in%
    c("GOTERM_BP_ALL", "GOTERM_MF_ALL", "GOTERM_CC_ALL"))
funChart2 = subset(funChart2, Category %in%
    c("GOTERM_BP_ALL", "GOTERM_MF_ALL", "GOTERM_CC_ALL"))
str(funChart1)
@

\section{Analysis and comparison}

Now that you have several functional annotation charts, we can start comparing and visualising them. If you had an entire directory of them, it's possible to generate a dendrogram from them to measure their similarity using the zTransformDirectory function - here, however, we will focus on finer comparison methods.\\
We can determine that almost no genes are shared by the two gene sets and there is next to no functional correlation by looking at the pairwise plots (Figure 1).\\
\begin{figure}
\begin{center}
<<label=fig1,fig=TRUE>>=
plotZScores(funChart1, funChart2)
@
\end{center}
\caption{Pairwise plot of Z scores for the two datasets}
\label{fig:one}
\end{figure}

Now, a great way to visualise the differences between these two sets is to use a directed acyclic graph of GO terms. Here, we colour each node based on the set or combinations of sets it originated from - yellow nodes are shared between two, red ones are the first input set, green ones are the second. In this case, there are several clear differences - funChart1 is enriched in oxygen and haeme binding, while funChart2 contains terms for transferase and protein kinase activity (Figure 2).\\
\begin{figure}
\begin{center}
<<label=fig2,fig=TRUE>>=
plotTwoGODags(funChart1, funChart2, ont="MF", cutoff=0.01)
@
\end{center}
\caption{Directed acyclic graph showing differences in GO term enrichment}
\label{fig:two}
\end{figure}

\end{document}
